### ISSUE TITLE
Java error

### ISSUE THREAD

**Issue by jpoor2** [TheFuckingRat/RatPoison#128]
Alright so I went to install rat poison and I’m having a lot of problems. Whenever I start the build process everything goes fine. The issue comes up whenever I try and actually run it. I get the java' is not recognized as a external or interal command" error. I have followed every guide to change the path to where to folder is located but no matter what I do it still shows the error. I’ve tried uninstalling java and reinstalling it several times. Same with rat poison. Any help would be greatly appreciated.

**Comment by jpoor2** [comment]
I just reinstalled and ran charlanto and it isnt having the same issue that rat poison is. Any idea why charlanto could find java and not rat poison?

**Comment by jpoor2** [comment]
One more thing lol. It will actually run if I open the java file instead of the .bat

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TheFuckingRat** [comment]
https://github.com/TheFuckingRat/RatPoison/issues/104 https://github.com/TheFuckingRat/RatPoison/issues/98 https://github.com/TheFuckingRat/RatPoison/issues/101 https://github.com/TheFuckingRat/RatPoison/issues/81
See these for extra information. Edit the .bat file and remove the line 'set path="%JAVA_HOME%";%path%' completely, that will most likely fix your issue. My guess for why would be because you have an 'Oracle\...' somewhere in your 'Path' system variables overwriting java_home

**Comment by jpoor2** [comment]
That fixed it, thank you so much!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
