### ISSUE TITLE
1.5 Suggestions

### ISSUE THREAD

**Issue by rattedpojzn** [TheFuckingRat/RatPoison#144]
I left the previous issue in case you want to answer it because it might help someone facing similar problems.After opening it, I saw that 1.5 was released. I like the new stuff and customization available, like the snaplines. I've been playing for a bit and here's what I noticed:

- Rifle smoothness doesn't work, be it at 1 or 5, it's still snapping with 1 click (path aim is enabled). Doesn't seem to be a problem with SMGs or pistols.
- Having trouble to make the hitmarker reappear. Hope it's possible to make the combo show up without having it enabled. When I first made the hitmarker and outline color transparent, it still displayed it as black.

**Comment by TheFuckingRat** [comment]
Are you sure rifle smoothness isn't working? It's setup exactly the same as smgs, pistols, etc, except for one string difference. I tested it in a map and it's updating values properly and you can visually see the aimbot being faster/slower. Changing speed and strictness also effect the 'snapping'/smoothness of it. Like having an aimspeed of 0, smoothness and strictness of 1 will snap, but changing smoothness to 5 slows it down considerably. Can't see to find an issue, can you double check?

I will change the combo to allow it to be used without the hitmarker, and unfortunately since the hitmarker has the fadeaway the alpha is controlled by the timing, and the color won't affect that part, so you can't make it invisible that way.

**Comment by rattedpojzn** [comment]
Sure, here's a video. I didn't render it, not sure if it will be available in 720p.
https://youtu.be/4qC1NVEq37A
I compared a pistol (P250), SMG (MP7) and rifle (Ak-47) on the same settings. It seems that the rifle fov doesn't work as well, changed it from 180 to 1 and it was still the same distance from which it triggers (blue glow).

**Comment by TheFuckingRat** [comment]
I know its currently not well designed or easy to tell, but you're editing the settings for the general RIFLE aim, your selected weapon in the menu is AK47, if you look at the 'Enable Override' checkbox its checked, meaning AK47 has override settings being used for the aimbot instead of the general RIFLE settings, so you'll need to check the 'Weapon Override' checkbox to edit the settings for the AK47 (or just check 'Weapon Override', uncheck 'Enable Override', then uncheck 'Weapon Override' again to disable it for that weapon)

**Comment by rattedpojzn** [comment]
Looks like that was the problem. Never noticed it happening before, looked like it's working fine for the other weapon types. Thanks for helping me out, looking forward to the new updates.
