### ISSUE TITLE
Black backround behind ESP/any graphic overlay.

### ISSUE THREAD

**Issue by getsmoked777** [TheFuckingRat/RatPoison#148]
![black ESP](https://user-images.githubusercontent.com/55365255/64999734-e2122c00-d8b6-11e9-83e7-49ae81880e9e.png)

I got ESP to work by enabling all visual performance settings under system properties. It doesn't instantly work but will if I alt tab the process a few times. Now the ESP is there but there is a constant black background behind everything. I use jdk 12. If I F1 or alt tab the black sometimes disappears along with all the ESP.

I am also on window borderless and Win7

**Comment by getsmoked777** [comment]
Surprisingly charlatano works until I enable skeleton ESP. Then it starts to have the same black background issue. If i use chams or glow only in charlatano it overlays everything well. Disabling both in ratpoison still has the black background issue.

**Comment by TheFuckingRat** [comment]
Windows 7 isnt supported is why, only Windows 10

**Comment by furioushell98** [comment]
@TheFuckingRat i tried Rat on windows7 (netcafé) i disabled menu and every walls settings (glow chams box esp except radar) aim on rifles/smgs worked and it didn't work on pistols/awp ( you have to hold fire button for aim to work which is not the case for pistols and snipers)

**Comment by TheFuckingRat** [comment]
@furioushell98 I appreciate you testing but it isn't really needed for W7 atleast. As I said it's not supported because I can't readily test it, though it's very unlikely that only half of it works and half doesn't, since nothing about CSGO is different and there's basically no difference in the categories for weapon types, so I'd assume its an issue with certain settings
