### ISSUE TITLE
How exactly does the "perfect bomb defuse" option meant to work?

### ISSUE THREAD

**Issue by Zayoe4** [TheFuckingRat/RatPoison#288]
I've found that it will make me go into a buy menu when passing through spawn. Is there a certain time I need to activate it?

Edit: figured out how to use it, but it does sometimes activate at the start of new rounds causing me to go into the buy menu

**Comment by matt1tk** [comment]
I put in a check to ensure it -use’s after the bomb goes off (specifically, if the code has already done a +use, and the bomb timer is negative, then apply a -use). It’s possible that it’s slightly buggy since i just put it in. I’ll do some more testing to avoid this. And does this happens at the beginning of any round, or just after you perfect defuse?

**Comment by matt1tk** [comment]
One possible fix is to disable “use key opens buy menu” in csgo settings (keyboard and mouse tab) but that’s kind of a band aid fix and i’m working on an actual fix.

**Comment by Zayoe4** [comment]
@matt1tk 
It always goes off at the start of every round in casual.
I don't play comp, so I can't speak to if it also does it there.

**Comment by matt1tk** [comment]
@Zayoe4 Working on fix

**Comment by matt1tk** [comment]
@Zayoe4 I cannot recreate this for some reason, would you be willing to test if what I changed fixes the issue?

**Comment by Zayoe4** [comment]
@matt1tk Sure, do you have a separate branch somewhere or do you need me to copy/paste some changes you made?

**Comment by matt1tk** [comment]
Ratpoisonrat seems to have a fix for it, waiting for his release

**Comment by matt1tk** [comment]
@Zayoe4 https://github.com/TheFuckingRat/RatPoison/tree/beta
