### ISSUE TITLE
Grandle error help

### ISSUE THREAD

**Issue by LoveyGoo** [TheFuckingRat/RatPoison#316]
ive tried everything i could find similar to this problem but i cant fix it ,
it happens on the start of the Build.bat file after you choose (y/n) 
i could use some help :/
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

**Comment by TheFuckingRat** [comment]
If a fresh download doesnt work, dont run as admin or anything, just run the build.bat normally, try building it with the folder on your desktop. Otherwise find a friend or someone to build it for you and send you the build folder, or just wait until 1.6 releases, will have a downloadable built version on the releases tab.

**Comment by LoveyGoo** [comment]
i have already tried the things you told me but its cool i got a triggerbot,radar,esp cheat for now , im going to wait for the 1.6 release ~thanks
