### ISSUE TITLE
RAM usage after 1 game was ~5gb

### ISSUE THREAD

**Issue by getsmoked777** [TheFuckingRat/RatPoison#408]
The process for rat poison starts out under 1gb.  Steadily rises and never stabilizes.  After one arms race match my RAM usage was around 5.5 GB.  I have tried lowering the overlay resolution to match my game res.  My csgo process uses around 900mb or so most times. I am on windows 10.

**Comment by matt1tk** [comment]
CSGO normally takes up lots of ram, more than 900 at least for me. Are you running anything else that would need ram? If not the ram is just sitting there not being used, so the system allows the JDK to use more memory. If it really is detrimental to using your PC try switching to the Adobe JDK, instead of OpenJDK. AFAIK it is poorer in memory management than regular JDK. Download: https://www.oracle.com/java/technologies/javase-jdk13-downloads.html

**Comment by getsmoked777** [comment]
Thank you I will try it in a bit.  I don't have anything else running and I also optimized win10 to use as little resources as possible.  The part that confuses me is that it steadily rises by 30 or so mb every few seconds until it ends up in the thousands,  even without much going on in game.  This is how my task manager looks like:
![whatt](https://user-images.githubusercontent.com/55365255/83361272-8e1c7a00-a355-11ea-87b4-08ff9a9220aa.PNG)

**Comment by matt1tk** [comment]
Yep, it seems certain now that the OpenJDK used now does not respect memory limits given in the command line. Use Oracle's JDK.

**Comment by matt1tk** [comment]
This is NOT an issue with OpenJDK. this is fixed by this commit (https://github.com/TheFuckingRat/RatPoison/commit/263b961e80d577a16e4a04d0a207e993bd433c41), simply replace "-Xms512m" with "-Xms32m -XX:+UseSerialGC"
