### ISSUE TITLE
MENU_APP doesn't working

### ISSUE THREAD

**Issue by JeeyM** [TheFuckingRat/RatPoison#72]
I'm trying to draw the overlay on "Untitled - Notepad" but the menu doesn't appear

**Comment by AStupidRat** [comment]
Dumb question but the notepad is opened and looks like https://gyazo.com/b4a754cbf32f1bd724d4157df80affac correct? Try a different application if possible such as notepad++

**Comment by JeeyM** [comment]
I already tried with WinRAR but the same problem, menu doesn't appear
https://imgur.com/a/yV5WgeY

**Comment by AStupidRat** [comment]
Will be addressed in a future update

**Comment by furioushell98** [comment]
I set the menu_app to Untitled - Notepad, then i maximized the application just like @AStupidRat said above and launched Ratpoison then went back to the game (Fullscreen) and it kinda worked i suppose, the overlay appeared in a new window, chams, radar, aimbot worked, the only things that didn't work are recoil crosshair, bomb timer. They only show up at the overlay's black window. When you press F1 the menu shows up on the same window and not in game, but it's fine. Thanks for that.

**Comment by AStupidRat** [comment]
@furioushell98 changing the menu app is meant to draw all overlay features (such as the menu, recoil crosshair, box esp, indicators, etc) on that application instead of the game. Going this route and without multiple monitors, you won't be able to utilize things like the bomb timer or spectator list, and because its not drawing ontop of the game, things like the recoil crosshair or box esp won't work at all. But you will be able to alt tab to the menu app and edit your settings using the menu instead of having to edit your settings in the files and full restarting. If you only want to use the cheat without modifying settings as you play, you can just disable the menu if you prefer. Also the window being a black application doesn't sound like its intended, it's meant to draw on top of the menu_app, which seems to be an issue with the latest build on github and will be addressed in a later update.

**Comment by furioushell98** [comment]
@AStupidRat that's exactly what i've been doing, alt tabbing to the black window where i can use the menu and change settings. I don't mind not having features like bomb timer and Recoil crosshair as long as radar and aim are working. Thank you for the explanation and the effort in making this cheat better.
